# Basic site settings
title: Your Portfolio
description: Frontend Developer | UI/UX Designer Portfolio
url: "https://yourusername.github.io"
baseurl: "/portfolio"  # If your repository name is different, change this

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
